image: alpine

before_script:
- apk update
- apk add doxygen


pages:
  script:
  - doxygen docs/Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
