image: alpine

before_script:
- apk update
- apk add doxygen
## Uncomment the following line if you use graphviz dot graphs
#- apk add ttf-freefont graphviz

pages:
  script:
  - doxygen doxygen/Doxyfile
  - mv documentation/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
