name: Main CI

on:
  pull_request:
    branches: [ main,dev ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - '**/CMakePresets.txt'
      - '**/cmake/**'
      - '**/vcpkg.json'
      - '.github/workflows/main_ci.yml'
      - 'codecov.yml'

  push:
    branches: [ main,dev ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/CMakeLists.txt'
      - '**/CMakePresets.txt'
      - '**/cmake/**'
      - '**/vcpkg.json'
      - '.github/workflows/main_ci.yml'
      - 'codecov.yml'
    tags-ignore:
      - '*'

  workflow_dispatch:

env:
  BUILD_TYPE: Debug
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg-cache

jobs:
  linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        config: [ gcc ]
        include:
          - config: gcc
            version: '14'

    steps:
      - uses: actions/checkout@v4
        with:
          path: cao

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: ${{ matrix.version }}

      - name: Setup Environment
        run: |
          echo "GCOV=gcov-${{ matrix.version }}" >> $GITHUB_ENV

          sudo apt install ninja-build gcovr liblz4-dev zlib1g-dev -y

      - name: Install Qt
        uses: kidev/install-qt-action@v4.5.0

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: ${{ github.workspace }}/cao/vcpkg.json

      - name: Configure & Build
        working-directory: ${{ github.workspace }}/cao
        run: |
          cmake --preset ninja-linux -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -Dcao_BUILD_DOCS=OFF
          cmake --build build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-x64
          path: |
            ${{ github.workspace }}/cao/build/src/Cathedral_Assets_Optimizer
      

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: cao

      - name: Install Qt
        uses: kidev/install-qt-action@v4.5.0

      - name: Setup MSVC (x64)
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: '**/cao/vcpkg.json'

      - name: (main) Configure & Build
        working-directory: ${{ github.workspace }}/cao
        run: |
          cmake --preset ninja-windows
          cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-x64
          path: |
            ${{ github.workspace }}/cao/build/src/Cathedral_Assets_Optimizer.exe
